### ISSUE TITLE
有debug.h吗？？

### ISSUE THREAD

**Issue by hijk1234** [lkytal/Gh0st2.0#4]
找人看了下，别人说
项目属性里平台工具集选的V141，需要修改，我选成V140，并修改了目标平台版本至我当前系统版本后，用VS2015SP3 编译，提示缺少文件#include "..\\..\\debug.h"，注释了之后一堆MsgErr之类的函数找不到定义，看起来是作者自己轮了一套输出消息的函数

**Comment by hijk1234** [comment]
人呢？在不在哦

**Comment by lkytal** [comment]
`#ifndef DEBUGHEADFILEFORCPP
#define DEBUGHEADFILEFORCPP

#define EQ(x, y) ( !lstrcmpi((x), (y)) )
#define lxsend(s, buf) send((s), (buf), lstrlen((buf)), 0)
#define lxrecv(s, buf) recv((s), (buf), sizeof((buf)), 0)
#define MsgBox(cap, text) MessageBoxEx(NULL, (text), (cap), MB_OK, 0001)
#define DbgErr DbpErr

CONST DWORD OPTIONS = FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS;
#define LOCALLANG MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT)

LPVOID __stdcall VirtualAlloc(size_t _size);
BOOL __stdcall VirtualFree(LPVOID lp, size_t _size);
HANDLE __stdcall CreateThread(LPTHREAD_START_ROUTINE lpaddr, LPVOID lp);
HANDLE __stdcall CreateThread(LPTHREAD_START_ROUTINE lpaddr);

int __cdecl ShowErrorMsg(LPCSTR pFormat, ...);
int __cdecl ShowErrorMsg(LPCWSTR pFormat, ...);
int __stdcall GetErr(WCHAR msg[]);
int __stdcall GetErr(CHAR msg[]);
int __cdecl ShowMsg(DWORD id);
int __cdecl ShowMsg(LPCWSTR pFormat, ...);
int __cdecl ShowMsg(LPCSTR pFormat, ...);

#if _MSC_VER >= 1900

#define DbpErr(...)
#define MsgErr(...)
#define Msg(...)
#define Log(...)
#define LogEx(...)
#define LogExTime(...)
#define recordEx(...)
#define Dbp(...)

#else

#define DbpErr(_X_)
#define MsgErr(_X_)
#define Msg(_X_)
#define Log(_X_)
#define LogEx(_X_,_Y_)
#define LogExTime(logfile, msg)
#define recordEx(_X_, _Y_)
#define Dbp(_X_)

#endif

#endif	//defined
`

**Comment by hijk1234** [comment]
缺少好多，ico,bmp等图片资源文件啊？老大，麻烦重新上传一份吧。根本无法编译。

**Comment by hijk1234** [comment]
394651947@qq.com  这是我的邮箱,麻烦传输一份给我吧,缺少的文件实在太多了.

**Comment by hijk1234** [comment]
人呢?在不在????

**Comment by hijk1234** [comment]
394651947@qq.com 这是我的邮箱,麻烦传输一份给我吧,缺少的文件实在太多了.
